Add conditional checks for review status

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,8 +3,6 @@ name: Release
 on:
   create:
   status:
-    state:
-      - success
   pull_request_review:
     types:
       - submitted
@@ -43,32 +41,42 @@ jobs:
     if: startsWith(github.event.pull_request.head.ref, 'release/') &&
       !github.event.pull_request.closed_at &&
       !github.event.pull_request.merged
-
-      # github.event.pull_request.mergeable_state == 'clean' &&
-      # github.event.pull_request.mergeable &&
-      # github.event.review.state == 'approved' &&
-      #
-      # rather than state approved, another possibility is to run on pull_request type unlocked
-      #	- assuming unlocked is when branch protections are met, ie status checks passed, approved by x reviewers, etc...
-      # If that's the case, then we also won't need closed_at and merged_at
-      # Though, we'll need to test that assumption, if a PR is updated after it's "unlocked", then what?
-      # on: pull_request:
-      #   types:
-      #     - unlocked
-      #
-      # If locked does not mean this, we need to also run when status checks complete and pass
-      #
     runs-on: ubuntu-latest
     steps:
-      - name: Output github
+      - name: Check if pull request is mergeable
         run: |
-          # approved
-          echo review state: ${{ github.event.review.state }}
-          echo pull request state: ${{ github.event.pull_request.state }}
-          echo pull request closed_at: ${{ github.event.pull_request.closed_at }}
-          echo pull request merged: ${{ github.event.pull_request.merged }}
-          echo pull request mergeable: ${{ github.event.pull_request.mergeable }}
-          echo pull request mergeable state: ${{ github.event.pull_request.mergeable_state }}
+          PR_REVIEWS=$(
+            curl ${{ github.event.pull_request.url }}/reviews |
+            jq '.[] |= { login: .user.login, state: .state } | reverse | unique_by( .login )'
+          )
+
+          PR_APPROVALS=$(
+            echo ${PR_REVIEWS} |
+            jq '[.[] | select( .state == "APPROVED" )] | length'
+          )
+          echo "This pull request has ${PR_APPROVALS} approvals"
+
+          PR_CHANGE_REQUESTS=$(
+            echo ${PR_REVIEWS} |
+            jq '[.[] | select( .state == "CHANGES_REQUESTED" )] | length'
+          )
+          echo "This pull request has ${PR_CHANGE_REQUESTS} reviewers requesting changes"
+
+          if [ ${PR_APPROVALS} -lt 1 ] || [ ${PR_CHANGE_REQUESTS} -gt 0 ]; then
+            echo "Exiting with failure"
+            exit 1
+          fi
+
+          MERGEABLE_STATE=$(
+            curl ${{ github.event.pull_request.url }} |
+            jq '.mergeable_state'
+          )
+          echo "The mergeable state of this pull request is ${MERGEABLE_STATE}"
+
+          if [ ${MERGEABLE_STATE} != "clean" ]; then
+            echo "Exiting with failure"
+            exit 1
+          fi
 
       - name: Merge into master
         run: echo "Merge into master"
